config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
   sessions:      'admins/sessions',
    passwords:     'admins/passwords',
   registrations: 'admins/registrations'
  }

  # adminのログアウト時にルーティングエラーになったため追加
  devise_scope :admin do
    get '/admins/sign_out' => 'admins/sessions#destroy'
  end

  devise_for :customers, controllers: {
    sessions:      'customers/sessions',
    passwords:     'customers/passwords',
    registrations: 'customers/registrations'
   }

  root :to => "customers/items#top"
  get "about" => "customers/items#about"

  resources :infomations do
     collection do
       get :thanks
     end
  end

  resources :order_items do
    resources :items
  end

  namespace :admins do
    resources :customers,only: [:index,:show,:edit,:update]
  	resources :items,only: [:index,:new,:create,:show,:edit,:update,]
  	resources :genres,only: [:index,:create,:edit,:update, :show]
  	resources :orders,only: [:index,:show,:update]

  end



  namespace :customers do
    resources :rates
    resources :items,only: [:index,:show]
    resources :cart_items do
      collection do
        delete :cart_destroy
      end
    end

  	resources :customers,only: [:show,:edit,:update] do
  		member do
        get :leave_page
        patch :leave
      end

      resources :cart_items,only: [:index,:update,:create,:destroy] do
        collection do
          delete :cart_destroy
        end
      end

      resources :orders,only: [:new,:index,:show,:create] do
        collection do
          post :log
          get :thanks
        end
      end

      resources :addresses,only: [:index,:create,:edit,:update,:destroy]
    end
  end
end

app/controllers/admins/customers_controller.rb
class Admins::CustomersController < ApplicationController

  def index
    @customers = Customer.all.order(params[:sort]).page(params[:page]).per(20)
    @data = [[Date.today.ago(6.days), @customers.created_6day_ago.count],
    [Date.today.ago(5.days), @customers.created_5day_ago.count],
    [Date.today.ago(4.days), @customers.created_4day_ago.count],
    [Date.today.ago(3.days), @customers.created_3day_ago.count],
    [Date.today.ago(2.days), @customers.created_2day_ago.count],
    [Date.yesterday, @customers.created_yesterday.count],
    [Date.today, @customers.created_today.count]]
    
  end

  def show
    @customer = Customer.find(params[:id])
    if @customer.is_deleted == false
      @status = "有効"
    else
      @status = "退会"
    end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admins_customer_path, notice: "You have updated genre successfully."
    else
      render "edit"
    end
  end

  end

  private
    def customer_params
     params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_deleted)
    end

end

app/controllers/admins/orders_controller.rb
class Admins::OrdersController < ApplicationController
  def index
    @orders = Order.search(params[:method]).page(params[:page]).per(20)
    @data = [[Date.today.ago(6.days), @orders.created_6day_ago.count],
    [Date.today.ago(5.days), @orders.created_5day_ago.count],
    [Date.today.ago(4.days), @orders.created_4day_ago.count],
    [Date.today.ago(3.days), @orders.created_3day_ago.count],
    [Date.today.ago(2.days), @orders.created_2day_ago.count],
    [Date.yesterday, @orders.created_yesterday.count],
    [Date.today, @orders.created_today.count]]
  end

  def show
    @order = Order.find(params[:id])
    @order_items = @order.order_items
  end

  def update
    @order = Order.find(params[:id])
    @order_items = @order.order_items
    @order_item = OrderItem.find(params[:id])
      @order.update_attributes!(order_params)
      if @order.status == "入金確認"
        OrderItem.multi_update(order_item_params)
        redirect_to admins_order_path(@order), notice: "You have updated status successfully."
      else
        redirect_to admins_order_path(@order), notice: "You have updated status successfully."
      end

  end

  private
    def order_params
      params.require(:order).permit(:customer_id, :postal_code, :address, :name, :shipping_cost, :total_payment, :payment_method, :status)
    end
    private

    def order_item_params
      params.require(:order).permit(order_items: :making_status)[:order_items]
    end
end

app/controllers/customers/addresses_controller.rb
class Customers::AddressesController < ApplicationController

  def index
    @address = Address.new
    @addresses = Address.where(customer_id: current_customer.id)
  end

  def create
    address = Address.new(address_params)
    address.customer_id = current_customer.id
    if address.save
      redirect_to request.referer
      flash[:notice] = "新しい配送先を登録しました。"
    else
      redirect_to request.referer
      flash[:notice] = "全ての項目を正しく入力してください。"
    end
  end

  def edit
    @address = Address.find(params[:id])
  end

  def update
    @address = Address.find(params[:id])
    if @address.update(address_params)
       redirect_to customers_customer_addresses_path(current_customer.id)
       flash[:notice] = "配送先を更新しました。"
    else
      render "edit"
      flash[:notice] = "全ての項目を正しく入力してください。"
    end
  end

  def destroy
    address = Address.find(params[:id])
    address.destroy
    redirect_to request.referer
  end

  private
  def address_params
    params.require(:address).permit(:name,:postal_code,:address)
  end
end

app/controllers/customers/cart_items_controller.rb
class Customers::CartItemsController < ApplicationController
  before_action :authenticate_customer!,except: [:create]

  def create
    if customer_signed_in?
      @cart_item = CartItem.new(cart_item_params)
      @cart_item.customer_id = current_customer.id
      order_item_amount = params[:cart_item][:amount]
      if order_item_amount.empty?
        flash[:order_item] = "数量を選択してください"
        redirect_to customers_item_path(@cart_item.item_id)
      elsif current_customer.cart_items.find_by(item_id: params[:cart_item][:item_id]).present?
        cart_item = current_customer.cart_items.find_by(item_id: params[:cart_item][:item_id])
        cart_item.amount += params[:cart_item][:amount].to_i
        cart_item.save
        flash[:notice] = "#{@cart_item.item.name}の数量を変更しました"
        redirect_to customers_cart_items_path(@cart_item)
      else
        @cart_item.save
        flash[:notice] = "#{@cart_item.item.name}をカートに追加しました"
        redirect_to customers_cart_items_path(@cart_item)
      end
    else
      flash[:order_item] = "カートに追加するにはログインしてください"
      redirect_to request.referer
    end
  end

  def index
    @cart_items = current_customer.cart_items.all
    @total = @cart_items.inject(0) { |sum, item| sum + item.sum_of_price }
  end

  def update
    @cart_item = CartItem.find(params[:id])
    if @cart_item.update(cart_item_params)
      flash.now[:notice] = "#{@cart_item.item.name}の数量を変更しました"
      @cart_items = current_customer.cart_items.all
      @total = @cart_items.inject(0) { |sum, item| sum + item.sum_of_price }
    end
  end

  def destroy
    @cart_item = CartItem.find(params[:id])
    @cart_items = current_customer.cart_items.all
    if @cart_item.destroy
      flash.now[:notice] = "#{@cart_item.item.name}をカートから削除しました"
      @total = @cart_items.inject(0) { |sum, item| sum + item.sum_of_price }
    end
  end

  def cart_destroy
    @cart_items = current_customer.cart_items.all
    if @cart_items.destroy_all
      redirect_to customers_cart_items_path(@cart_items)
    end
  end

  private

  def cart_item_params
    params.require(:cart_item).permit(:amount, :item_id)
  end

end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/customers_controller.rb
class Customers::CustomersController < ApplicationController

  def show
    @customer = Customer.find(params[:id])
  end

  def leave_page
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to customers_customer_path(@customer)
      flash[:notice] = "会員情報を更新しました。"
    else
      render "edit"
    end
  end

  def leave_page
    @customer = Customer.find(params[:id])
  end

  def leave
    customer = Customer.find(params[:id])
    customer.update(is_deleted: true)
    reset_session
    flash[:notice] = "退会手続きが完了しました。またのご利用お待ちしております。"
    redirect_to root_path
  end

  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code,:email, :address, :telephone_number, :is_deleted)
  end

end

app/controllers/customers/items_controller.rb
class Customers::ItemsController < ApplicationController

  def top
    @items = Item.all
    @all_ranks = Item.find(OrderItem.group(:item_id).order('count(item_id) desc').limit(4).pluck(:item_id))
  end

  def about
  end

  def index
    @items = Item.search(params[:search]).page(params[:page]).per(8)
    @amount = @items.total_count
    @genres = Genre.all
  end

  def show
    @item = Item.find(params[:id])
    @cart_item = CartItem.new
    @genres = Genre.all
    
    if customer_signed_in?
      unless Count.find_by(customer_id: current_customer.id, item_id: @item.id)
        current_customer.counts.create(item_id: @item.id)
      end
    else
    end
    
  end

end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/orders_controller.rb
class Customers::OrdersController < ApplicationController

  def new
    @customer= Customer.find(params[:customer_id])
    @address= Address.find_by(customer_id: params[:customer_id])
    @addresses= Address.where(customer_id: @customer.id)
    @order= Order.new
  end

  def log
    @customer= Customer.find(params[:customer_id])
    @addresses= Address.where(customer_id: @customer.id)
    @cart_items= CartItem.where(customer_id: @customer.id)
    total_price= []
    @cart_items.each do |cart_item|
      total_price << cart_item.item.taxin_price * cart_item.amount
    end
    @total_price= total_price.sum
    @total_payment= @total_price + 800

    @order= Order.new(order_params)
    cart_item_order = params[:order][:oter_address]
    if params[:order][:address_select] == "0"
       @order_postal_code= @customer.postal_code
       @order_address= @customer.address
       @order_name= @customer.last_name + @customer.first_name
    elsif params[:order][:address_select] == "1"
      if cart_item_order.empty?
            flash.now[:alert1] = "選択肢の中から宛先を選んでください"
            render "new"
      else
         @order_postal_code = Address.find_by(id: params[:order][:oter_address], customer_id: @customer.id).postal_code
         @order_address = Address.find_by(id: params[:order][:oter_address], customer_id: @customer.id).address
         @order_name = Address.find_by(id: params[:order][:oter_address], customer_id: @customer.id).name
      end
    elsif params[:order][:address_select] == "2"
       @order_postal_code= @order.postal_code
       @order_address= @order.address
       @order_name= @order.name
       if @order_postal_code.blank? || @order_address.blank? || @order_name.blank?
            flash.now[:alert2] = "郵便番号,住所,宛名は全て入力してください"
            render "new"
       end
    end
  end

  def create

    order= Order.new(order_params)
    order.customer_id = current_customer.id
    @cart_items = current_customer.cart_items

    if order.save
      @cart_items.each do |cart_item|
      @order_item = OrderItem.new
      @order_item.order_id = order.id
      @order_item.item_id = cart_item.item.id
      @order_item.amount = cart_item.amount
      @order_item.price = cart_item.amount * cart_item.item.taxin_price
      @order_item.save
       end
     @cart_items.destroy_all
     redirect_to thanks_customers_customer_orders_path(current_customer.id)
    else

    end
  end

  def thanks
  end


  def index
    @orders= Order.where(customer_id: current_customer.id)
  end

  def show
    @order= Order.find(params[:id])
    @orders= Order.where(customer_id: params[:customer_id])
    @order_items= OrderItem.where(order_id: @order.id)
    total_price= []
    @order_items.each do |order_item|
      total_price << order_item.item.taxin_price * order_item.amount
    end
    @total_price= total_price.sum
    @total_payment= @total_price + 800
  end

  private

  def order_params
    params.require(:order).permit(:postal_code, :address, :name, :shipping_cost, :total_payment, :payment_method, :status)
  end

end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/rates_controller.rb
class Customers::RatesController < ApplicationController
  before_action :authenticate_customer!

  def show
    @item = Item.find(params[:id])
    @rate = Rate.new
    @current_user = current_customer.id
  end

  def create
    @rate = Rate.new(rate_params)
    @item = @rate.item
    if @rate.save
      redirect_to customers_item_path(@item), notice: "ありがとうございました。"
    else
      redirect_to customers_item_path(@item), notice: "すでに投稿済みです。"
    end

  end

  private
    def rate_params
     params.require(:rate).permit(:star,:customer_id,:item_id)
    end


end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    customers_customer_path(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    customers_customer_path(resource)
  end

end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/customers/addresses_helper.rb
module Customers::AddressesHelper
end

app/helpers/customers/cart_items_helper.rb
module Customers::CartItemsHelper
end

app/helpers/customers/customers_helper.rb
module Customers::CustomersHelper
end

app/views/customers/orders/index.html.erb
<div class="order-index">
  <h3>注文履歴一覧</h3>
  <div class="index-box">
    <table>
      <tr>
        <th style="width:10%">注文日</th>
        <th style="width:20%">配送先</th>
        <th style="width:20%">注文商品</th>
        <th style="width:10%">支払金額</th>
        <th style="width:10%">ステータス</th>
        <th style="width:10%">注文詳細</th>
      </tr>
      <% if @orders.count == 0 %>
      <tr class= "index-border">
        <td></td>
        <td></td>
        <td class= "text-right">注文履歴はありません</td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      <% else %>
        <% @orders.each do |order| %>
        <tr class= "index-border">
          <td class="text-center"><%= order.created_at.strftime("%Y/%m/%d").to_s %></td>
          <td>
            <ul>
              <li>〒<%= order.postal_code %></li>
              <li><%= order.address %></li>
              <li><%= order.name %></li>
            </ul>
          </td>
          <td>
            <ul>
              <% order.order_items.each do |order| %>
              <li><%= order.item.name %></li>
              <% end %>
            </ul>
          </td>
          <td class="text-center"><%= (order.total_payment).to_s(:delimited) %>円</td>
          <td class="text-center"><%= order.status_i18n %></td>
          <td class="text-center"><%= link_to "表示する", customers_customer_order_path(current_customer.id,order.id), class: "btn btn-secondary" %></td>
        </tr>
        <% end %>
      <% end %>
    </table>
  </div>
</div>

app/views/customers/orders/log.html.erb
<div class= "line-image"><%= image_tag "order-line3.jpg" ,class: "order-line"%></div>
<h3 class="order-show-title">注文情報確認</h3>
<div class= "order-contents">

  <div class="left-side">
    <div class= "order">
      <h5 class=" w-75">注文内容</h5>
      <table>
        <tr>
          <th></th>
          <th style="width:35%">商品名</th>
          <th style="width:18%">単価(税込)</th>
          <th style="width:15%">数量</th>
          <th style="width:17%">小計</th>
        </tr>
        <% @cart_items.each do |cart_item| %>
          <tr>
            <td><%= attachment_image_tag cart_item.item, :image, size: "50x50" %></td>
            <td><%= cart_item.item.name %></td>
            <td class="text-center"><%= cart_item.item.taxin_price.to_s(:delimited) %>円</td>
            <td class="text-center"><%= cart_item.amount %>個</td>
            <td class="text-center"><%= (cart_item.item.taxin_price * cart_item.amount).to_s(:delimited) %>円</td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>

  <div class= "right-side">
    <div class= "cost">
      <h5>請求情報</h5>
      <table>
        <tr>
          <th>商品合計</th>
          <td><%= @total_price.to_s(:delimited) %>円</td>
        </tr>
        <tr>
          <th>送料</th>
          <td><%= 800 %>円</td>
        </tr>
        <tr>
          <th>請求金額</th>
          <td><%= (@total_price + 800).to_s(:delimited)  %>円</td>
        </tr>
      </table>
    </div>

    <div class= "info">
      <h5>注文情報</h5>
      <table class="info-table">
        <tr>
          <th>お届け先</th>
          <td>
            <ul>
              <li>〒<%= @order_postal_code %></li>
              <li><%= @order_address %></li>
              <li><%= @order_name %></li>
            </ul>
          </td>
        </tr>
        <tr>
          <th>支払方法</th>
          <td><%= @order.payment_method_i18n %></td>
        </tr>
      </table>

  <%= form_with model: @order,url: customers_customer_orders_path(@customer.id), method: :post, local: true do |f| %>
    <%= f.hidden_field :customer_id, value: current_customer.id %>
    <%= f.hidden_field :shipping_cost, value: 800 %>
    <%= f.hidden_field :total_payment, value: @total_payment %>
    <% if params[:order][:address_select] == "0" %>
      <%= f.hidden_field :postal_code, value: @order_postal_code %>
      <%= f.hidden_field :address,value: @order_address %>
      <%= f.hidden_field :name,value: @order_name %>
    <% elsif params[:order][:address_select] == "1" %>
      <%= f.hidden_field :postal_code, value: @order_postal_code %>
      <%= f.hidden_field :address,value: @order_address %>
      <%= f.hidden_field :name,value: @order_name %>
    <% elsif params[:order][:address_select] == "2" %>
      <%= f.hidden_field :postal_code, value: @order_postal_code %>
      <%= f.hidden_field :address,value: @order_address%>
      <%= f.hidden_field :name,value: @order_name %>
    <% end %>
    <div class="log-btn"><%=f.submit '注文を確定する',class: "btn btn-danger" %></div>
  <% end %>
    </div>
  </div>
</div>

app/views/customers/orders/new.html.erb
  <div class= "frame">
    <div class= "line-image"><%= image_tag "order-line2.jpg" ,class: "order-line"%></div>
    <h3>お客様情報入力</h3>
    <div class= "main-contents">
    <%= form_with(model: @order,url: log_customers_customer_orders_path(@customer.id),method: :post, local: true) do |f| %>
      <div class= "paymethod-form">
        <h5>お支払方法</h5>
        <div class= "payment_method-btn">
          <ul>
            <li class= "radio-btn">
              <label><%= f.radio_button :payment_method, :クレジットカード, checked: true%>クレジットカード</label>
            </li>
            <li  class= "radio-btn">
              <label><%= f.radio_button :payment_method, :銀行振込 %>銀行振込</label>
            </li>
          </ul>
        </div>
      </div>
      <div class= "address-form">
        <h5>お届け先</h5>
        <div class= "address-btn">
          <ul>
            <li  class= "radio-btn">
              <%= f.radio_button :address_select,0 ,checked: true %><%= f.label :address_select, "ご自身の住所", value: 0 %>
              <div class= "my-address">
                <div>
                  〒<%= @customer.postal_code %>
                  <%= @customer.address %>
                </div>
                <div>
                  <%= @customer.full_name %>
                </div>
              </div>
            </li>
            <li  class= "radio-btn">
              <div class=" text-center" style="color: red;"><%= flash[:alert1] %></div>
              <%= f.radio_button :address_select,1 %><%= f.label :address_select,"登録済み住所から選択", value: 1 %>
              <%= f.collection_select :oter_address, @addresses, :id, :full_address, include_blank: "選択して下さい" %>
            </li>
            <li>
              <div class= "radio-btn"><%= f.radio_button :address_select,2%><%= f.label :address_select,"新しいお届け先", value: 2 %></div>
              <div class=" text-center" style="color: red;"><%= flash[:alert2] %></div>
              <table class= "another-address">
                <tr>
                  <th><%= f.label "郵便番号（ハイフンなし）" %></th>
                  <td><%= f.text_field :postal_code %></td>
                </tr>
                <tr>
                  <th><%= f.label "住所" %></th>
                  <td class= "another-address-address"><%= f.text_field :address %></td>
                </tr>
                <tr>
                  <th><%= f.label "宛名" %></th>
                  <td><%= f.text_field :name %></td>
                </tr>
              </table>
            </li>
          </ul>
        </div>
      </div>
      <div class= "check-btn-area">
        <div class= "check-btn"><%= f.submit "確認画面へ進む", class: "btn btn-primary" %></div>
      </div>
    </div>
    <% end %>
  </div>

app/views/customers/orders/show.html.erb
<h3 class="order-show-title">注文履歴詳細</h3>
<div class= "order-contents">

  <div class="left-side">
    <div class= "order">
      <h5 class=" w-75">注文内容</h5>
      <table>
        <tr>
          <th style="width:30%">商品名</th>
          <th style="width:20%">単価(税込)</th>
          <th style="width:20%">数量</th>
          <th style="width:15%">小計</th>
        </tr>
        <% @order.order_items.each do |order| %>
        <tr>
          <td><%= order.item.name %></td>
          <td class="text-center"><%= (order.item.taxin_price).to_s(:delimited) %>円</td>
          <td class="text-center"><%= order.amount %>個</td>
          <td class="text-center"><%= (order.item.taxin_price * order.amount).to_s(:delimited) %>円</td>
        </tr>
        <% end %>
      </table>
    </div>
  </div>

  <div class= "right-side">
    <div class= "cost">
      <h5>請求情報</h5>
      <table>
        <tr>
          <th>商品合計</th>
          <td><%= @total_price.to_s(:delimited) %>円</td>
        </tr>
        <tr>
          <th>配送料</th>
          <td><%= (@order.shipping_cost).to_s(:delimited) %>円</td>
        </tr>
        <tr>
          <th>ご請求額</th>
          <td><%= @total_payment.to_s(:delimited) %>円</td>
        </tr>
      </table>
    </div>


    <div class= "info">
      <h5>注文情報</h5>
      <table>
        <tr>
          <th>注文日</th>
          <td><%= @order.created_at.strftime("%Y/%m/%d").to_s %></td>
        </tr>
        <tr>
          <th>配送先</th>
          <td>
            <ul>
              <li>〒<%= @order.postal_code %></li>
              <li><%= @order.address %></li>
              <li><%= @order.name %></li>
            </ul>
          </td>
        </tr>
        <tr>
          <th>支払方法</th>
          <td><%= @order.payment_method_i18n %></td>
        </tr>
        <tr>
          <th>ステータス</th>
          <td><%= @order.status_i18n %></td>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/customers/orders/thanks.html.erb
<div class= "line-image"><%= image_tag "order-line4.jpg" ,class: "order-line"%></div>
<div class="thanks-main">
  <div class="thanks-message">
    <h2>お買い上げありがとうございます。</h2>
    <p>商品の到着まで今しばらくお待ちください。</p>
  </div>
  <div class="thanks-btn">
    <%= link_to root_path do %>
      <button type="button" class="btn btn-secondary">トップページに戻る</button>
    <% end %>
  </div>
</div>