config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
   sessions:      'admins/sessions',
    passwords:     'admins/passwords',
   registrations: 'admins/registrations'
  }

  # adminのログアウト時にルーティングエラーになったため追加
  devise_scope :admin do
    get '/admins/sign_out' => 'admins/sessions#destroy'
  end

  devise_for :customers, controllers: {
    sessions:      'customers/sessions',
    passwords:     'customers/passwords',
    registrations: 'customers/registrations'
   }

  root :to => "customers/items#top"
  get "about" => "customers/items#about"

  resources :infomations do
     collection do
       get :thanks
     end
  end

  resources :order_items do
    resources :items
  end

  namespace :admins do
    resources :customers,only: [:index,:show,:edit,:update]
  	resources :items,only: [:index,:new,:create,:show,:edit,:update,]
  	resources :genres,only: [:index,:create,:edit,:update, :show]
  	resources :orders,only: [:index,:show,:update]

  end



  namespace :customers do
    resources :rates
    resources :items,only: [:index,:show]
    resources :cart_items do
      collection do
        delete :cart_destroy
      end
    end

  	resources :customers,only: [:show,:edit,:update] do
  		member do
        get :leave_page
        patch :leave
      end

      resources :cart_items,only: [:index,:update,:create,:destroy] do
        collection do
          delete :cart_destroy
        end
      end

      resources :orders,only: [:new,:index,:show,:create] do
        collection do
          post :log
          get :thanks
        end
      end

      resources :addresses,only: [:index,:create,:edit,:update,:destroy]
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_items, dependent: :destroy
  has_many :counts, dependent: :destroy
  has_many :rates, dependent: :destroy
  attachment :image
  
  
  def avg_score
    unless self.rates.empty?
      rates.average(:star).round(1)
    else
      0.0
    end
  end

  def taxin_price
    (price*1.08).round
  end

  def self.search(search)
    if search
      Item.where(['name LIKE ?', '%'+search+'%'])
    else
      Item.all
    end
  end

  with_options presence: true do
    validates :image
    validates :name
    validates :introduction
    validates :price, numericality: { only_integer: true, message: "は半角数字で入力してください" }
  end


end

app/controllers/admins/items_controller.rb
class Admins::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:notice] = "#{@item.name}を登録しました"
      redirect_to admins_item_path(@item)
    else
      render :new
    end
  end

  def index
    @items = Item.all.page(params[:page]).per(10)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:notice] = "商品内容を変更しました"
      redirect_to admins_item_path(@item)
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_active)
  end
end

app/controllers/customers/items_controller.rb
class Customers::ItemsController < ApplicationController

  def top
    @items = Item.all
    @all_ranks = Item.find(OrderItem.group(:item_id).order('count(item_id) desc').limit(4).pluck(:item_id))
  end

  def about
  end

  def index
    @items = Item.search(params[:search]).page(params[:page]).per(8)
    @amount = @items.total_count
    @genres = Genre.all
  end

  def show
    @item = Item.find(params[:id])
    @cart_item = CartItem.new
    @genres = Genre.all
    
    if customer_signed_in?
      unless Count.find_by(customer_id: current_customer.id, item_id: @item.id)
        current_customer.counts.create(item_id: @item.id)
      end
    else
    end
    
  end

end

app/helpers/admins/items_helper.rb
module Admins::ItemsHelper
end

app/helpers/customers/items_helper.rb
module Customers::ItemsHelper
end

app/views/admins/items/_form.html.erb
<table class="admin-item-form-table">
  <tr><th>商品画像</th><td class="admin-item-img pl-0"><%= f.attachment_field :image, class: 'form-control-file' %></td></tr>
  <tr><th>商品名</th><td><%= f.text_field :name, class: 'form-control', placeholder: "商品名" %></td></tr>
  <tr><th>商品説明</th><td><%= f.text_area :introduction, class: "form-control", placeholder: "ここに説明文を記述します" %></td></tr>
  <tr><th>ジャンル</th><td><%= f.collection_select :genre_id, Genre.all, :id, :name, prompt: "-- 選択してください --" %></td></tr>
　<tr><th>税抜価格</th><td><%= f.text_field :price, class: "form-control", placeholder: "1000" %></td></tr>
　<tr><th>販売ステータス</th><td><%= f.select :is_active, {"販売中": true, "販売停止中": false} %></td></tr>
</table>

app/views/admins/items/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>商品編集</h2>
      <%= render 'layouts/errors', obj: @item %>
      <%= form_with model: @item, url: admins_item_path, local:true do |f| %>
        <%= render 'form', f: f %>
        <div class="form-group row justify-content-center mt-3">
          <%= f.submit "変更を保存", class: 'btn btn-success' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admins/items/index.erb
<div class="container">
  <div class="row">
    <div class='col-sm-12 col-md-10 col-lg-8 px-5 px-sm-0 mx-auto text-center'>
      <h2>商品一覧</h2>
      <div class="text-right">
        <%= link_to new_admins_item_path, class: "admin-item-link" do %>
          <i class="fa fa-plus fa-lg mb-2"></i>
        <% end %>
      </div>
      <table class="table table-hover">
        <thead>
          <tr>
            <th>ID</th>
            <th>商品名</th>
            <th>税抜価格</th>
            <th>ジャンル</th>
            <th>閲覧数</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
        <% @items.each do |item| %>
          <tr>
            <td><%= item.id %></td>
            <td class="align-middle text-left">
              <%= link_to admins_item_path(item), class:"link-style" do %>
                <%= attachment_image_tag item, :image, size:"60x40" %>
                <%= "　"+item.name %>
              <% end %>
            </td>
            <td class="align-middle"><%= item.price.to_s(:delimited) %></td>
            <td class="align-middle"><%= item.genre.name %></td>
            <td class="align-middle view-count"><%= item.counts.count %></td>
            <td class="align-middle">
              <% if item.is_active == true %>
      					<p class="is-active-true">販売中</p>
      				<% elsif item.is_active == false %>
      					<p class="is-active-false">販売停止中</p>
      				<% end %>
      			</td>
          </tr>
        <% end %>
        </tbody>
      </table>
      <div class="mb-5"><%= paginate @items %></div>
    </div>
  </div>
</div>

app/views/admins/items/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-9 col-lg-6 px-5 px-sm-0 mx-auto">
      <h2>商品新規登録</h2>
      <%= render 'layouts/errors', obj: @item %>
      <%= form_with model: @item, url: admins_items_path, local:true do |f| %>
        <%= render 'form', f: f %>
        <div class="form-group row justify-content-center mt-3">
          <%= f.submit "新規登録", class: 'btn btn-success' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admins/items/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-9 col-lg-6 px-5 px-sm-0 mx-auto">
      <h2 class="mb-3">商品詳細</h2>
      <div>
        <div class="text-center">
          <%= attachment_image_tag @item, :image, size:"300x200" %>
        </div>
        <div class="admin-item-show-detail">
          <table class="table admin-item-show-table">
            <tbody>
              <tr><th>商品名</th><td><%= @item.name %></td></tr>
              <tr><th>商品説明</th><td><%= @item.introduction %></td></tr>
              <tr><th>ジャンル</th><td><%= @item.genre.name %></td></tr>
              <tr><th>税込価格(税抜価格)</th><td><%= @item.taxin_price.to_s(:delimited) %> (<%= @item.price.to_s(:delimited) %>) 円</td></tr>
              <tr><th>販売ステータス</th>
              <td>
                <% if @item.is_active == true %>
        					<p class="is-active-true">販売中</p>
        				<% elsif @item.is_active == false %>
        					<p class="is-active-false">販売停止中</p>
        				<% end %>
              </td></tr>
            </tbody>
          </table>
          <div class="text-center">
            <%= link_to "編集する", edit_admins_item_path(@item), class: "btn btn-success" %>
            <%= link_to "一覧に戻る", admins_items_path, class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>