config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
   sessions:      'admins/sessions',
    passwords:     'admins/passwords',
   registrations: 'admins/registrations'
  }

  # adminのログアウト時にルーティングエラーになったため追加
  devise_scope :admin do
    get '/admins/sign_out' => 'admins/sessions#destroy'
  end

  devise_for :customers, controllers: {
    sessions:      'customers/sessions',
    passwords:     'customers/passwords',
    registrations: 'customers/registrations'
   }

  root :to => "customers/items#top"
  get "about" => "customers/items#about"

  resources :infomations do
     collection do
       get :thanks
     end
  end

  resources :order_items do
    resources :items
  end

  namespace :admins do
    resources :customers,only: [:index,:show,:edit,:update]
  	resources :items,only: [:index,:new,:create,:show,:edit,:update,]
  	resources :genres,only: [:index,:create,:edit,:update, :show]
  	resources :orders,only: [:index,:show,:update]

  end



  namespace :customers do
    resources :rates
    resources :items,only: [:index,:show]
    resources :cart_items do
      collection do
        delete :cart_destroy
      end
    end

  	resources :customers,only: [:show,:edit,:update] do
  		member do
        get :leave_page
        patch :leave
      end

      resources :cart_items,only: [:index,:update,:create,:destroy] do
        collection do
          delete :cart_destroy
        end
      end

      resources :orders,only: [:new,:index,:show,:create] do
        collection do
          post :log
          get :thanks
        end
      end

      resources :addresses,only: [:index,:create,:edit,:update,:destroy]
    end
  end
end

app/controllers/admins/customers_controller.rb
class Admins::CustomersController < ApplicationController

  def index
    @customers = Customer.all.order(params[:sort]).page(params[:page]).per(20)
    @data = [[Date.today.ago(6.days), @customers.created_6day_ago.count],
    [Date.today.ago(5.days), @customers.created_5day_ago.count],
    [Date.today.ago(4.days), @customers.created_4day_ago.count],
    [Date.today.ago(3.days), @customers.created_3day_ago.count],
    [Date.today.ago(2.days), @customers.created_2day_ago.count],
    [Date.yesterday, @customers.created_yesterday.count],
    [Date.today, @customers.created_today.count]]
    
  end

  def show
    @customer = Customer.find(params[:id])
    if @customer.is_deleted == false
      @status = "有効"
    else
      @status = "退会"
    end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admins_customer_path, notice: "You have updated genre successfully."
    else
      render "edit"
    end
  end

  end

  private
    def customer_params
     params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_deleted)
    end

end

app/controllers/admins/items_controller.rb
class Admins::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:notice] = "#{@item.name}を登録しました"
      redirect_to admins_item_path(@item)
    else
      render :new
    end
  end

  def index
    @items = Item.all.page(params[:page]).per(10)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:notice] = "商品内容を変更しました"
      redirect_to admins_item_path(@item)
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_active)
  end
end

app/controllers/customers/addresses_controller.rb
class Customers::AddressesController < ApplicationController

  def index
    @address = Address.new
    @addresses = Address.where(customer_id: current_customer.id)
  end

  def create
    address = Address.new(address_params)
    address.customer_id = current_customer.id
    if address.save
      redirect_to request.referer
      flash[:notice] = "新しい配送先を登録しました。"
    else
      redirect_to request.referer
      flash[:notice] = "全ての項目を正しく入力してください。"
    end
  end

  def edit
    @address = Address.find(params[:id])
  end

  def update
    @address = Address.find(params[:id])
    if @address.update(address_params)
       redirect_to customers_customer_addresses_path(current_customer.id)
       flash[:notice] = "配送先を更新しました。"
    else
      render "edit"
      flash[:notice] = "全ての項目を正しく入力してください。"
    end
  end

  def destroy
    address = Address.find(params[:id])
    address.destroy
    redirect_to request.referer
  end

  private
  def address_params
    params.require(:address).permit(:name,:postal_code,:address)
  end
end

app/controllers/customers/cart_items_controller.rb
class Customers::CartItemsController < ApplicationController
  before_action :authenticate_customer!,except: [:create]

  def create
    if customer_signed_in?
      @cart_item = CartItem.new(cart_item_params)
      @cart_item.customer_id = current_customer.id
      order_item_amount = params[:cart_item][:amount]
      if order_item_amount.empty?
        flash[:order_item] = "数量を選択してください"
        redirect_to customers_item_path(@cart_item.item_id)
      elsif current_customer.cart_items.find_by(item_id: params[:cart_item][:item_id]).present?
        cart_item = current_customer.cart_items.find_by(item_id: params[:cart_item][:item_id])
        cart_item.amount += params[:cart_item][:amount].to_i
        cart_item.save
        flash[:notice] = "#{@cart_item.item.name}の数量を変更しました"
        redirect_to customers_cart_items_path(@cart_item)
      else
        @cart_item.save
        flash[:notice] = "#{@cart_item.item.name}をカートに追加しました"
        redirect_to customers_cart_items_path(@cart_item)
      end
    else
      flash[:order_item] = "カートに追加するにはログインしてください"
      redirect_to request.referer
    end
  end

  def index
    @cart_items = current_customer.cart_items.all
    @total = @cart_items.inject(0) { |sum, item| sum + item.sum_of_price }
  end

  def update
    @cart_item = CartItem.find(params[:id])
    if @cart_item.update(cart_item_params)
      flash.now[:notice] = "#{@cart_item.item.name}の数量を変更しました"
      @cart_items = current_customer.cart_items.all
      @total = @cart_items.inject(0) { |sum, item| sum + item.sum_of_price }
    end
  end

  def destroy
    @cart_item = CartItem.find(params[:id])
    @cart_items = current_customer.cart_items.all
    if @cart_item.destroy
      flash.now[:notice] = "#{@cart_item.item.name}をカートから削除しました"
      @total = @cart_items.inject(0) { |sum, item| sum + item.sum_of_price }
    end
  end

  def cart_destroy
    @cart_items = current_customer.cart_items.all
    if @cart_items.destroy_all
      redirect_to customers_cart_items_path(@cart_items)
    end
  end

  private

  def cart_item_params
    params.require(:cart_item).permit(:amount, :item_id)
  end

end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/customers_controller.rb
class Customers::CustomersController < ApplicationController

  def show
    @customer = Customer.find(params[:id])
  end

  def leave_page
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to customers_customer_path(@customer)
      flash[:notice] = "会員情報を更新しました。"
    else
      render "edit"
    end
  end

  def leave_page
    @customer = Customer.find(params[:id])
  end

  def leave
    customer = Customer.find(params[:id])
    customer.update(is_deleted: true)
    reset_session
    flash[:notice] = "退会手続きが完了しました。またのご利用お待ちしております。"
    redirect_to root_path
  end

  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code,:email, :address, :telephone_number, :is_deleted)
  end

end

app/controllers/customers/items_controller.rb
class Customers::ItemsController < ApplicationController

  def top
    @items = Item.all
    @all_ranks = Item.find(OrderItem.group(:item_id).order('count(item_id) desc').limit(4).pluck(:item_id))
  end

  def about
  end

  def index
    @items = Item.search(params[:search]).page(params[:page]).per(8)
    @amount = @items.total_count
    @genres = Genre.all
  end

  def show
    @item = Item.find(params[:id])
    @cart_item = CartItem.new
    @genres = Genre.all
    
    if customer_signed_in?
      unless Count.find_by(customer_id: current_customer.id, item_id: @item.id)
        current_customer.counts.create(item_id: @item.id)
      end
    else
    end
    
  end

end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/orders_controller.rb
class Customers::OrdersController < ApplicationController

  def new
    @customer= Customer.find(params[:customer_id])
    @address= Address.find_by(customer_id: params[:customer_id])
    @addresses= Address.where(customer_id: @customer.id)
    @order= Order.new
  end

  def log
    @customer= Customer.find(params[:customer_id])
    @addresses= Address.where(customer_id: @customer.id)
    @cart_items= CartItem.where(customer_id: @customer.id)
    total_price= []
    @cart_items.each do |cart_item|
      total_price << cart_item.item.taxin_price * cart_item.amount
    end
    @total_price= total_price.sum
    @total_payment= @total_price + 800

    @order= Order.new(order_params)
    cart_item_order = params[:order][:oter_address]
    if params[:order][:address_select] == "0"
       @order_postal_code= @customer.postal_code
       @order_address= @customer.address
       @order_name= @customer.last_name + @customer.first_name
    elsif params[:order][:address_select] == "1"
      if cart_item_order.empty?
            flash.now[:alert1] = "選択肢の中から宛先を選んでください"
            render "new"
      else
         @order_postal_code = Address.find_by(id: params[:order][:oter_address], customer_id: @customer.id).postal_code
         @order_address = Address.find_by(id: params[:order][:oter_address], customer_id: @customer.id).address
         @order_name = Address.find_by(id: params[:order][:oter_address], customer_id: @customer.id).name
      end
    elsif params[:order][:address_select] == "2"
       @order_postal_code= @order.postal_code
       @order_address= @order.address
       @order_name= @order.name
       if @order_postal_code.blank? || @order_address.blank? || @order_name.blank?
            flash.now[:alert2] = "郵便番号,住所,宛名は全て入力してください"
            render "new"
       end
    end
  end

  def create

    order= Order.new(order_params)
    order.customer_id = current_customer.id
    @cart_items = current_customer.cart_items

    if order.save
      @cart_items.each do |cart_item|
      @order_item = OrderItem.new
      @order_item.order_id = order.id
      @order_item.item_id = cart_item.item.id
      @order_item.amount = cart_item.amount
      @order_item.price = cart_item.amount * cart_item.item.taxin_price
      @order_item.save
       end
     @cart_items.destroy_all
     redirect_to thanks_customers_customer_orders_path(current_customer.id)
    else

    end
  end

  def thanks
  end


  def index
    @orders= Order.where(customer_id: current_customer.id)
  end

  def show
    @order= Order.find(params[:id])
    @orders= Order.where(customer_id: params[:customer_id])
    @order_items= OrderItem.where(order_id: @order.id)
    total_price= []
    @order_items.each do |order_item|
      total_price << order_item.item.taxin_price * order_item.amount
    end
    @total_price= total_price.sum
    @total_payment= @total_price + 800
  end

  private

  def order_params
    params.require(:order).permit(:postal_code, :address, :name, :shipping_cost, :total_payment, :payment_method, :status)
  end

end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/rates_controller.rb
class Customers::RatesController < ApplicationController
  before_action :authenticate_customer!

  def show
    @item = Item.find(params[:id])
    @rate = Rate.new
    @current_user = current_customer.id
  end

  def create
    @rate = Rate.new(rate_params)
    @item = @rate.item
    if @rate.save
      redirect_to customers_item_path(@item), notice: "ありがとうございました。"
    else
      redirect_to customers_item_path(@item), notice: "すでに投稿済みです。"
    end

  end

  private
    def rate_params
     params.require(:rate).permit(:star,:customer_id,:item_id)
    end


end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    customers_customer_path(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    customers_customer_path(resource)
  end

end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :reject_user, only: [:create]

  protected

  def reject_user
    @customer = Customer.find_by(email: params[:customer][:email].downcase)
    if @customer
      if (@customer.valid_password?(params[:customer][:password]) && (@customer.active_for_authentication? == false))
        flash[:error] = "退会済みです"
        redirect_to new_customer_session_path
      end
    else
      flash[:error] = "登録情報が見つかりません"
    end
  end


  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/admins/items_helper.rb
module Admins::ItemsHelper
end

app/helpers/customers/addresses_helper.rb
module Customers::AddressesHelper
end

app/helpers/customers/cart_items_helper.rb
module Customers::CartItemsHelper
end

app/helpers/customers/customers_helper.rb
module Customers::CustomersHelper
end

app/views/customers/items/_item_each.html.erb
<% items.each do |item| %>
  <div class="mx-4 mt-3 w-20">
    <%= link_to customers_item_path(item), class: "link-style" do %>
      <div class="item-img-box2"><%= attachment_image_tag item, :image, size:"230x170" %></div>
      <p class="item-index-name mt-1"><%= item.name %></p>
    <% end %>
    ￥<%= item.taxin_price.to_s(:delimited) %>
    <% if item.is_active == false %>
      <p class="sold-out">sold out</p>
    <% end %>
  </div>
<% end %>

app/views/customers/items/_rank.html.erb
<% all_ranks.each.with_index(1) do |item, i| %>
  <div class="mx-auto text-center">
    <h5>第<%= i %>位</h5>
    <%= link_to customers_item_path(item), class: "link-style" do %>
      <div class="item-img-box"><%= attachment_image_tag item, :image, size:"250x190" %></div>
      <div class="item-index-name mt-2"><%= item.name %></div>
    <% end %>
    ￥<%= item.taxin_price.to_s(:delimited) %>
  </div>
<% end %>

app/views/customers/items/about.html.erb
<div class="about-image">
  <h2 class="text-center">いらっしゃいませ</h2><br><br>
  <p>ながのCAKEは全国発送可能なケーキ屋さんです。<br><br>
  お子様からお年寄りの方までお召し上がりいただけるよう、<br><br>
  様々なバリエーションをご用意しております。<br><br>
  また、全国へ発送可能ですので「いつ」でも「どこ」でもご注文いただけます。<br><br>
  ぜひご注文ください。
  </p>
</div>
<div class='container px-5 mt-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-12 mx-auto'>
      <div class="chef">
        <div class="chef-img">
          <%= image_tag "chef.jpg", size: "400x400" %>
        </div>
        <div class="chef-introduction">
          <h5>OWNER CHEF</h5>
          <h2 class= "text-left">KEKIO NAGANO</h2>
          <h3 class= "mt-4">「とりあえずやってみる」</h3>
          <p>
            今更やったって....　　追いつけるわけがない.....<br>
            そんな考えで夢を諦めていませんか？<br>
            一流シェフと呼ばれる人たちも、最初は初心者です。<br>
            私も最近クックパッド見ながらようやくクッキーが作れるようになりました。<br>
            皆さんもプログラミングを始めたばかりだと思いますが、<br>
            初心者同士、一緒に頑張りましょう。
          </p>
          <p>
            【プロフィール】<br>
          　１９７７年生まれ。<br>
            大学卒業後、合同会社DMM.comに入社。<br>
            2020年に脱サラし、長野県阿智村に「ながのCAKE」をOPENする。
          </p>
        </div>
      </div>
      <h3 class="text-center">ACCESS</h3>
      <div class= "accsess">
        <div class="accsess-text">
          <table>
            <tr>
              <th>店舗名</th>
              <td>ながのCAKE</td>
            </tr>
            <tr>
              <th>住所</th>
              <td>長野県○-×-△</td>
            </tr>
            <tr>
              <th>電話番号</th>
              <td><%= link_to do %>0120-117-117<% end %></td>
            </tr>
            <tr>
              <th>営業時間</th>
              <td>２４時間年中無休</td>
            </tr>
            <tr>
              <th>アクセス</th>
              <td>都心から車で約５時間</td>
            </tr>
            <tr>
              <th>駐車場</th>
              <td>１０台駐車可能</td>
            </tr>
          </table>
          　<div class="sns mb-5">
              <%= link_to do %><%= image_tag "insta.jpg", size: "30x30" %><% end %>&nbsp;
              <%= link_to do %><%= image_tag "face.jpg", size: "30x30" %><% end %>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/customers/items/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-12 mx-auto text-center'>
      <% @genres.each do |genre| %>
        <%= link_to genre.name, admins_genre_path(genre), class: "link-style2 mx-3" %>
      <% end %>
      <h3 class="mt-3">商品一覧（全 <%= @amount %> 件）</h3>
      <div class="item-index d-flex flex-wrap mt-3 mx-auto">
        <%= render "item_each", items: @items %>
      </div>
      <%= paginate @items %>
    </div>
  </div>
</div>

app/views/customers/items/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-12 mx-auto mb-5 text-center'>
      <% @genres.each do |genre| %>
        <%= link_to genre.name, admins_genre_path(genre), class: "link-style2 mx-3" %>
      <% end %>
    </div>
  </div>
  <div class='row'>
    <div class='col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto item-show'>
      <div class="mx-3">
        <%= attachment_image_tag @item, :image, size:"500x380" %>
      </div>
      <div class="item-detail mx-3">
        <div class="item-show-name"><%= @item.name %></div><br>
        <div><%= @item.introduction %></div><br>
        <div>￥<%= @item.taxin_price.to_s(:delimited) %>（税込）</div><br>
        <div>
          <%= link_to "レビュー", customers_rate_path %>
          <div class="d-flex">
            <div id="rate_<%= @item.id %>"></div>
              <script>
                $('#rate_<%= @item.id %>').raty({
                  size: 20,
                  starOff:  '<%= asset_path('star-off.png') %>',
                  starOn : '<%= asset_path('star-on.png') %>',
                  starHalf: '<%= asset_path('star-half.png') %>',
                  half: true,
                  readOnly: true,
                  score: <%= @item.avg_score %>,
                });
              </script>
            <div class="mx-2"><%= @item.avg_score %></div>
          </div>
        </div>
        <div class="mt-4">
          <% if @item.is_active == true %>
            <%= form_with model: @cart_item, url: customers_cart_items_path do |f| %>
              <%= f.hidden_field :item_id, value: @item.id %>
              <div style="color: red;"><%= flash[:order_item] %></div>
              <%= f.select :amount, options_for_select((1..10).to_a), include_blank: "個数選択" %><br>
              <%= f.submit "カートに入れる", class: "btn btn-success" %>
            <% end %>
          <% else %>
            <p class="sold-out-show">sold out</p>
          <% end %>
          <br><br><br>
          <%= link_to "一覧に戻る", customers_items_path, class:"return-index" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/customers/items/top.html.erb
<div class="main_imgBox my-3">
  <div class="main_img" style="background-image: url(assets/top/cheesecake.jpg)"></div>
  <div class="main_img" style="background-image: url(assets/top/mountain.jpg)"></div>
  <div class="main_img" style="background-image: url(assets/top/strawberrycake.jpg)"></div>
  <div class="main_img" style="background-image: url(assets/top/cupcake.jpeg)"></div>
  <div class="main_img" style="background-image: url(assets/top/loghouse.jpeg)"></div>
  <div class="main_img" style="background-image: url(assets/top/meringue.jpeg)"></div>
</div>

<div class='container'>
  <div class='row'>
    <div class='col-md-12 mx-auto'>
      <div class="text-center mt-5 mb-4">
        ようこそ、ながのCAKEへ！<br><br>
        このサイトは、ケーキ販売のECサイトになります。<br><br>
        会員でない方も商品の閲覧はできますが、<br><br>
        購入には会員登録が必要になります。
      </div>
      <h3>新着商品</h3>
      <div class="item-index d-flex flex-wrap mt-3">
        <% @items.last(4).reverse_each do |item| %>
          <div class="mx-auto text-center">
            <%= link_to customers_item_path(item), class: "link-style" do %>
              <div class="item-img-box"><%= attachment_image_tag item, :image, size:"250x190" %></div>
              <div class="item-index-name mt-2"><%= item.name %></div>
            <% end %>
            ￥<%= item.taxin_price.to_s(:delimited) %>
          </div>
        <% end %>
      </div>
      <h3 class="mt-5">人気ランキング</h3>
      <div class="item-index d-flex flex-wrap mt-3">
        <%= render 'rank', all_ranks: @all_ranks %>
      </div>
      <br>
      <p class="text-right"><%= link_to "全ての商品を見る", customers_items_path, class: "link-style2" %></p>
    </div>
  </div>
</div>